### ISSUE TITLE
ncm2

### ISSUE THREAD

**Issue by coachshea** [gaalcaras/ncm-R#13]
I love this plugin. Thank you so much for it. With ncm depracated, I'm wondering if this is going to be ported to work with ncm2.

Thanks again for your wonderful plugin.

**Comment by hughshuwang** [comment]
Same question here. Seems like it’s not working properly (at least for all functionalities showed) with ncm2 + ncm-R, and the key remapping for <c-n> and <c-p> is not working.

**Comment by gaalcaras** [comment]
Hi there,

Unfortunately, I had to put ncm-R on the back burner for a while, mainly because I had to switch from R to Python for work, so I rarely used ncm-R myself anymore.

The good news is, I temporarily had to work on a R project last week, and not having R completion with ncm2 was frustrating, so I've been working on updating ncm-R to make it work with ncm2.

I'm keeping it on a [feature branch](https://github.com/gaalcaras/ncm-R/tree/ncm2) for now. Would you mind trying it and telling me if it works for you? If that's the case I'll merge it to the main branch.

**Comment by coachshea** [comment]
I certainly understand catering to work demands, but I (perhaps selfishly) am glad that you had that R project to work on last week. I'll have some time this weekend to try it out and I'd be happy to do that and get back to you.

Thank you again for your great work!

**Comment by hughshuwang** [comment]
Glad to hear that you made the update! Appreciate your time and will try it out on weekend. Will get back to you soon.

Thanks! This is awesome work.

**Comment by coachshea** [comment]
I had an interesting experience trying this out. On my home computer (a debian and the main computer  I use with this) I could not get it to work. I thought that there might have been a conflict with an existing plugin and I didn't have time to sort it out (I have quite a few plugins), so I decided to try a fresh install on my work computer (a mac; I should point out that I am a high school math teacher and a hobbyist programmer, so my work computer mainly just takes attendance). I only included the necessary plugins to make this work and it worked fairly well, but I did not get completions of knitr options inside of code chunks, which I did previously. Is that something that I should be getting, or did that require additional plugins/settings that I've forgotten?  I'll have more time over the next week or so to play around with it and I'll be happy to keep trying things out for you, but that's what I've got so far.

Thanks again.

**Comment by gaalcaras** [comment]
Thanks for your feedback, I appreciate it.

> Is that something that I should be getting, or did that require additional plugins/settings that I've forgotten?

Yes, you should get rchunk completion, although there is a small bug that I can't seem to fix right now. Rchunk completion doesn't work the first time it's loaded, so you have to quit insert mode, go back and then it will work every time.

You can try [the following minimal vimrc](https://github.com/gaalcaras/ncm-R/blob/ncm2/test/min_vimrc) that I use for testing. Another way to test ncm-R is to run `./test/nvim_init` and check the logs with something like `tail /tmp/log_py3_* | grep --color "\[ncmR\]"`.

This is what you should see for rchunks:

```log
2018-11-18 22:58:33,444 [INFO @ rsource.py:_info:60] 3303 - [ncmR] rchunk :: init
2018-11-18 22:58:46,961 [INFO @ rsource.py:_info:60] 3303 - [ncmR] ncm_rchunk :: option: None, typed: ", ",ccol: 8, scope_len: 3
```

Please tell me if you find out what was preventing completion from working in your debian vimrc, maybe we can avoid conflicts in the future.

**Comment by gaalcaras** [comment]
The `ncm2` feature branch has now been merged to `master`, you can start using it instead of the feature branch, which has been deleted.

I'm also closing this issue since the switch to ncm2 has been completed. **Please open a new issue** if you run into a bug or have questions.
