### ISSUE TITLE
ncm-R not working with the latest Python neovim client

### ISSUE THREAD

**Issue by heygent** [gaalcaras/ncm-R#14]
I recently updated neovim and neovim-python on my machine, and ncm-R started to give this error on the first completion:

```
"hello.R" 1L, 22C
[ncm_r@yarp] Traceback (most recent call last):
[ncm_r@yarp]   File "/home/user/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py", line 59, in <module>
[ncm_r@yarp]     module_obj = importlib.import_module(module)
[ncm_r@yarp]   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
[ncm_r@yarp]     return _bootstrap._gcd_import(name[level:], package, level)
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
[ncm_r@yarp]   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
[ncm_r@yarp]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[ncm_r@yarp]   File "/home/user/.config/nvim/plugged/ncm-R/pythonx/ncm_r.py", line 11, in <module>
[ncm_r@yarp]     from neovim.api.nvim import NvimError
[ncm_r@yarp] ModuleNotFoundError: No module named 'neovim.api.nvim'
[ncm_r@yarp] Job is dead. cmd=['/usr/bin/python3', '-u', '/home/user/.config/nvim/plugged/nvim-yarp/pythonx/yarp.py', '/tmp/nvimmpgwBu/0', 3, 'ncm_r']
```

Replacing `neovim.api.nvim` with `neovim.api` in the pythonx folder fixes the problem on my machine.
I don't know whether that causes problems with previous versions of the client though. I'm submitting a pull request with the changes soon.

**Comment by sjewo** [comment]
Replacing neovim.api.nvim with neovim.api works for me too (NVIM v0.3.1, python-neovim 0.3.1).

**Comment by marskar** [comment]
I had this same problem and the solution here works for me too.

**Comment by c1au6i0** [comment]
I have the exact same error but the folder `pythonx` does not contain the file at all. Not sure why. Any hint? The folder contains only `yarp.py`

**Comment by eliotbehr** [comment]
> I have the exact same error but the folder `pythonx` does not contain the file at all. Not sure why. Any hint? The folder contains only `yarp.py`

Did you ever figure it out? I also have the same issue with ncm-R showing yarp dead etc. and no pythonx folder

**Comment by c1au6i0** [comment]
@eliotbehr I did not. I realized that `ncm-R` is not  maintained anymore and so I moved to another plugin
https://github.com/neoclide/coc.nvim  .  `COC` works well and provides same functionalities
