### ISSUE TITLE
Autocomplete only recognizes base package.

### ISSUE THREAD

**Issue by chrisvacc** [gaalcaras/ncm-R#16]
I ran Sys.getenv("NCM_R”) which returns “TRUE” and still no luck.

macOS Mojave

I use both NVIM and Vim with a shared .vimrc, same issue in both

```
NVIM v0.3.4
```
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Dec 13 2018 08:58:43)
```
```
R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)
```
Works fine with base package:

![](https://i.imgur.com/oD320Qa.png)

but installed libraries, no bueno:

![](https://i.imgur.com/7Kgq8Rq.png)

**Comment by gaalcaras** [comment]
Thanks for your input.

Have you loaded the ggplot2 package by calling `library(ggplot2)`? Unless a non default package is loaded, you will only get completion from base packages.

If you'd like to change which packages are considered default by Nvim-R, you can look at `help R_start_libs`.

**Comment by jalvesaq** [comment]
I think the issue was fixed by https://github.com/jalvesaq/Nvim-R/commit/6ff799026e0505127ad1cb0118dc0f01b7cd8b13

@chrisvacc could you confirm, please?

**Comment by chrisvacc** [comment]
Hi, yes it was. Sorry, I forgot to reply back.

**Comment by gaalcaras** [comment]
Awesome, thanks @jalvesaq!
